# Generated by Django 4.2.6 on 2023-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='descriptions',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
