# Generated by Django 4.2.6 on 2023-10-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ticket_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
