# Generated by Django 4.2.6 on 2023-10-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_activeticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeticket',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
