# Generated by Django 4.2.6 on 2023-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_activeticket_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeticket',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activeticket',
            name='start_date',
            field=models.DateField(),
        ),
    ]
